# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 192bb839ef95a12a687da95beddf64c6a4be803a2db3c577b3f7ebb73b7ed6fe244926a069d147a28aa0efb7c789d16a9af1c880d4eaefe9b6bccd5a59637c83

test:
  secret_key_base: f49d794cf32107c946feb21f26aa9fe16b329ebd68f857074a2c2cffb884156c4781feb499f507c5dd61c19a57825a872be10bbf1b8c598313f8fa97e1f1052a

production:
  secret_key_base: dca27bac17d8a58931f6b3a65bdedf38f24e103416d640d32147e7f782bc234d2e1ed4deda4dff837baac797dfa16600965fb732ea0e5e4ea740772f13c36ae9
